# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(4095, 839)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1300, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/jpg/images/background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_form = QtWidgets.QLabel(self.centralwidget)
        self.lineEdit_form.setGeometry(QtCore.QRect(480, 250, 321, 341))
        self.lineEdit_form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px")
        self.lineEdit_form.setText("")
        self.lineEdit_form.setObjectName("lineEdit_form")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(500, 270, 281, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(40, 0, 40, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lineEdit_title.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_title.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lineEdit_title.setBaseSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.lineEdit_title.setFont(font)
        self.lineEdit_title.setStyleSheet("font-size:60px;\n"
"font-weight:999")
        self.lineEdit_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.verticalLayout.addWidget(self.lineEdit_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("font-size:25px;\n"
"  background: transparent;\n"
"  padding: 0;\n"
"  border: 0;\n"
"  border-bottom: 2px solid silver;\n"
"  border-radius: 0%;\n"
"\n"
"  color: 000;")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        spacerItem2 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("font-size:25px;\n"
"  background: transparent;\n"
"  padding: 0;\n"
"  border: 0;\n"
"  border-bottom: 2px solid silver;\n"
"  border-radius: 0%;\n"
"\n"
"  color: 000;")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton.setMaximumSize(QtCore.QSize(110, 48))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font-size:25px;\n"
"border-radius:6px;\n"
"font-weight:999;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(90, 194, 198);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalFrame.raise_()
        self.lineEdit_title.raise_()
        self.lineEdit_username.raise_()
        self.lineEdit_password.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_title.setText(_translate("MainWindow", "登录"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "用户名"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "密码"))
        self.pushButton.setText(_translate("MainWindow", "登  录"))
import background_rc
