# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CourseSave.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 502)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 521, 501))
        self.widget.setStyleSheet("background-color:#f8fbf4")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(190, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 111, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_courseName = QtWidgets.QTextEdit(self.widget)
        self.textEdit_courseName.setGeometry(QtCore.QRect(220, 150, 191, 31))
        self.textEdit_courseName.setStyleSheet("border: 2px solid #64645e;\n"
" border-radius: 8px;")
        self.textEdit_courseName.setObjectName("textEdit_courseName")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(400, 390, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: 2px solid #64645e;\n"
"border-radius: 15px;")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(120, 240, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_courseCode = QtWidgets.QTextEdit(self.widget)
        self.textEdit_courseCode.setGeometry(QtCore.QRect(220, 250, 191, 31))
        self.textEdit_courseCode.setStyleSheet("border: 2px solid #64645e;\n"
" border-radius: 8px;")
        self.textEdit_courseCode.setObjectName("textEdit_courseCode")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "课程保存"))
        self.label.setText(_translate("Form", "课程保存"))
        self.label_2.setText(_translate("Form", "课程名称："))
        self.pushButton.setText(_translate("Form", "提交"))
        self.label_3.setText(_translate("Form", "课程号："))
