# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GradeSave.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 502)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, -10, 521, 511))
        self.widget.setStyleSheet("background-color:#f8fbf4")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(380, 420, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: 2px solid #64645e;\n"
"border-radius: 15px;")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(140, 340, 61, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_score = QtWidgets.QTextEdit(self.widget)
        self.textEdit_score.setGeometry(QtCore.QRect(220, 350, 191, 31))
        self.textEdit_score.setStyleSheet("border: 2px solid #64645e;\n"
" border-radius: 8px;")
        self.textEdit_score.setObjectName("textEdit_score")
        self.comboBox_name = QtWidgets.QComboBox(self.widget)
        self.comboBox_name.setGeometry(QtCore.QRect(220, 100, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.comboBox_name.setFont(font)
        self.comboBox_name.setObjectName("comboBox_name")
        self.comboBox_course = QtWidgets.QComboBox(self.widget)
        self.comboBox_course.setGeometry(QtCore.QRect(220, 220, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.comboBox_course.setFont(font)
        self.comboBox_course.setObjectName("comboBox_course")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(90, 220, 111, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(140, 100, 61, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "成绩保存"))
        self.label.setText(_translate("Form", "成绩保存"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.label_3.setText(_translate("Form", "分数："))
        self.label_4.setText(_translate("Form", "课程名称："))
        self.label_5.setText(_translate("Form", "姓名："))
